#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
REACT_INDEX="$ROOT/connect-query-es/packages/connect-query/src/index.ts"
VUE_INDEX="$ROOT/src/index.ts"
README="$ROOT/README.md"
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

# Extract named exports from export { ... } blocks (multiline safe, skips export *)
parse_exports() {
  tr '\n' ' ' < "$1" \
    | grep -oE 'export[[:space:]]+(type[[:space:]]+)?\{[^}]+\}' \
    | grep -oE '\{[^}]+\}' \
    | tr -d '{}' \
    | tr ',' '\n' \
    | sed 's/^[[:space:]]*//; s/[[:space:]]*$//; s/.*[[:space:]]as[[:space:]]*//' \
    | grep -v '^$' \
    | sort
}

parse_exports "$REACT_INDEX" > "$TMP/react_raw"
parse_exports "$VUE_INDEX"   > "$TMP/vue"

# Apply framework-specific name mappings (React name → Vue equivalent)
# These are APIs that exist in both frameworks under different names.
sed 's/^TransportProvider$/provideTransport/' "$TMP/react_raw" | sort > "$TMP/react"

comm -12 "$TMP/react" "$TMP/vue" > "$TMP/implemented"
comm -23 "$TMP/react" "$TMP/vue" > "$TMP/missing"
comm -13 "$TMP/react" "$TMP/vue" > "$TMP/extra"

TOTAL=$(wc -l < "$TMP/react" | tr -d ' ')
IMPL=$(wc -l < "$TMP/implemented" | tr -d ' ')
PCT=$((IMPL * 100 / TOTAL))

[ "$PCT" -ge 80 ] && COLOR=brightgreen || { [ "$PCT" -ge 50 ] && COLOR=yellow || COLOR=red; }

printf '\nAPI Coverage: %d%% (%d/%d)\n' "$PCT" "$IMPL" "$TOTAL"
printf 'Implemented: %s\n' "$(tr '\n' ' ' < "$TMP/implemented")"
printf 'Missing    : %s\n' "$(tr '\n' ' ' < "$TMP/missing")"
printf 'Vue-only   : %s\n' "$(tr '\n' ' ' < "$TMP/extra")"

{
  printf '<!-- coverage:start -->\n\n'
  printf '### API Coverage vs connect-query (official)\n\n'
  printf '![API Coverage](https://img.shields.io/badge/API%%20Coverage-%d%%25-%s)\n\n' "$PCT" "$COLOR"
  printf 'Implements **%d%%** (%d/%d) of the exports from the official [`@connectrpc/connect-query`](https://github.com/connectrpc/connect-query-es).\n\n' "$PCT" "$IMPL" "$TOTAL"
  printf '| Status | API |\n| --- | --- |\n'
  sed 's/.*/| ✅ Implemented | `&` |/' "$TMP/implemented"
  sed 's/.*/| ❌ Not yet     | `&` |/' "$TMP/missing"
  sed 's/.*/| 🔵 Vue-only    | `&` |/' "$TMP/extra"
  printf '\n> Auto-generated by `vp run update-coverage`.\n\n'
  printf '<!-- coverage:end -->'
} > "$TMP/section"

if grep -q '<!-- coverage:start -->' "$README"; then
  awk -v sec="$TMP/section" '
    /<!-- coverage:start -->/ { while ((getline line < sec) > 0) print line; skip=1; next }
    /<!-- coverage:end -->/ { skip=0; next }
    !skip
  ' "$README" > "$TMP/readme"
  mv "$TMP/readme" "$README"
  echo "README: updated between markers"
else
  printf '\n\n' >> "$README"
  cat "$TMP/section" >> "$README"
  echo "README: markers not found, appended to end"
fi
